Makefile: delete unused broken rule
$ make ./results/nangate45/gcd/base/5_route.v
[deleted]
[INFO ORD-0030] Using 20 thread(s).
Error: write_verilog.tcl, 1 can't read "::env(ODB_FILE)": no such variable
make: *** [Makefile:826: results/nangate45/gcd/base/5_route.v] Error 1

The correct syntax, which works, is:

$ make 5_route.odb.v

Signed-off-by: Øyvind Harboe <oyvind.harboe@zylin.com>