synth: replace silent error with some sort of error
If ADDER_MAP_FILE is not a file, then produce an error instead of
silence:

$ make ADDER_MAP_FILE=blah do-yosys
[deleted]
ERROR: Can't open input file `blah' for reading: No such file or directory
ERROR: TCL interpreter returned an error: Yosys command produced an error

Signed-off-by: Øyvind Harboe <oyvind.harboe@zylin.com>